# Create base builder image
FROM golang:1.14
WORKDIR /go/src/github.com/ava-labs/ortelius

# Install deps
RUN apt-get update && apt-get install -y librdkafka-dev

# Build app
COPY . .
RUN go get ./... && \
    GOOS=linux GOARCH=amd64 go build -o /opt/ortelius-client ./client/bin/main.go

# Wire in app
VOLUME /var/log/ortelius
VOLUME /var/lib/ortelius
ENTRYPOINT ["/opt/ortelius-client"]
