drop index cvm_transactions_txdata_trace_to_addr on cvm_transactions_txdata_trace;
drop index cvm_transactions_txdata_trace_from_addr on cvm_transactions_txdata_trace;
drop index tx_pool_msg_key on tx_pool;
